version: "3.7"

services:
  db:
    image: mongo:4.2
    volumes:
      - db:/data/db

  explore:
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: db
    ports:
      - 5001:8081

  app:
    image: node:12-alpine
    command: sh -c "yarn install && yarn dev"
    working_dir: /app
    user: "1002:1002"
    ports:
      - 5000:5000
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /home:/home
      - ${PWD}:/app
    environment:
      MONGO_URL: mongodb://db/dev
      APP_PORT: 5000
      APP_ADDR: 0.0.0.0
      APP_SECURITY_SECRET: o5QstfCE/axBDI1jOaxNpLJyxsJsJLw45a0kjB+6n0EoNJxCRU0y3iU6WM7B6Pvx

volumes:
  db: